env:
  TERM: "xterm"

# https://buildkite.com/docs/pipelines/command-step
steps:
  - label: "print environment"
    command:
      - "npm install -g print-arch @bahmutov/print-env"
      - "print-arch"
      - "print-env BUILDKITE"

  - "wait"

  - label: "install"
    command:
      - "npm install"
      - "$(npm bin)/commit-message-install --else \"npm install cypress\""
      - "$(npm bin)/run-if npm run cypress:version"

  - "wait"

  - label: "run"
    command: "$(npm bin)/run-if npm run cypress:run -- --record"

  - "wait"

  - label: "check video file"
    command:
      - "$(npm bin)/run-if npm run check-videos"
      - "$(npm bin)/run-if npm run list-videos"
